### ISSUE TITLE
do not require title/image for research items

### ISSUE THREAD

**Issue by reissler** [comparative/cap#102]
Hi Geoff,

One of the scholars from the Danish Project sent this feedback to me, so just passing it along:

"One minor thing: I am typing in the publication references for the Danish page, and I cannot see the need to type in a title and put in an image. This works for a book, but not a journal article. It looks weird when I leave these pieces blank. So I suggest to erase these options."

Best,
Rebecca

**Comment by comparative** [comment]
Make image/title optional for research items
