### ISSUE TITLE
twitter and youtube hrefs

### ISSUE THREAD

**Issue by comparative** [comparative/cap#130]

**Comment by ejfagan** [comment]
YouTube URL: https://www.youtube.com/channel/UC2t4GDRFsah3YPTj4lqS1BQ

Twitter URL: https://twitter.com/policyagendas

**Comment by ejfagan** [comment]
Fixed Twitter for sidebar.html (we changed the Twitter account name):

<a class="twitter-timeline" href="https://twitter.com/policyagendas/lists/cap" data-widget-id="679744747179798528">Tweets from https://twitter.com/policyagendas/lists/cap</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
