### ISSUE TITLE
Where do new pages show up?

### ISSUE THREAD

**Issue by reissler** [comparative/cap#136]
Hi Geoff,

I had a quick question. As a website administrator, I have the ability to add pages to the site. However, I am not sure how or where they would show up on the front end. I tried to create a “Website Sponsorship” page (the response I have gotten from some of the money people is that our initial solution is not satisfactory), but while the “Website Sponsorship” page that I created shows up in the backend, it doesn’t show in the front. 

How should I set this up so that if I have to create new pages in the future, I don’t have to bug you? If it is the case that only you can do this, then let me know so that I can be sure of the wording and placement before you make any changes.

**Comment by ejfagan** [comment]
Just the static URL. No navigation:

http://www.comparativeagendas.net/pages/website-sponsorship

**Comment by comparative** [comment]
EJ is correct -- custom pages have a URL, they can be linked to e.g. in WYSIWYG boxes but they do not generate any nav elements!

(I can add new nav elements if you let me know where.)
