### ISSUE TITLE
http://comparativeagendas.net does not work

### ISSUE THREAD

**Issue by ejfagan** [comparative/cap#138]
www.comparativeagendas.net goes to the proper webpage. http://comparativeagendas.net is blank, except for the GoDaddy placeholder page. Can we fix this? Modern browsers make the distinction between the two URLs difficult for users. Some websites use http:// as the default, some use www, but all forward the 'wrong' one to the 'right' one.

**Comment by comparative** [comment]
This will be fixed when we move to LAITS servers! 

(since app is not at it's permanent IP address I just created a CNAME record for now)
