### ISSUE TITLE
preserve search criteria with saved charts?

### ISSUE THREAD

**Issue by reissler** [comparative/cap#145]
I made a new slide for the CAP home page (It is a duplicate of the old one about Belgium's legislative agenda). While clicking on the slide does lead to the properly filled in trends tool, the selectors on the left side of the trends tool are all empty. 
[Trends bug.pdf](https://github.com/comparative/cap/files/81576/Trends.bug.pdf)

**Comment by comparative** [comment]
This would be a pretty big change.

**Comment by reissler** [comment]
Don't worry about this one. I was mistaken about how I thought the site was
supposed to work. Now that I understand I am happy with how it is. As far
as I am concerned close this one, too.
Rebecca
