### ISSUE TITLE
Problem Deleting Datasets and Research Entries--Bug

### ISSUE THREAD

**Issue by reissler** [comparative/cap#150]
Currently, when someone tries to delete a dataset or a research entry, the user gets sent to a blank screen and the contents are not deleted. I received this bug from a couple of different teams and was able to replicate it myself. This is the screen you get: 
![image001](https://cloud.githubusercontent.com/assets/13875132/12517919/f270f9e6-c0fa-11e5-94de-b1f16ccee2e7.png)

**Comment by comparative** [comment]
This was a new bug I introduced by moving to http file storage (pre-requisite for launch on LAITS servers!)

Should be fixed, sorry and thanks for finding it.

G
