### ISSUE TITLE
Source Description box empty when "All Topics" is selected

### ISSUE THREAD

**Issue by reissler** [comparative/cap#159]
This is true of all datasets except State of the Union for some reason.

**Comment by comparative** [comment]
Put a message saying drilldown not available... instances for all topics is a potentially huge list not really suited to this UI -- can users just download the dataset if they want all instances??

Good eye re: State of the Union!! it was a red herring -- instances coming up were for topic ZERO (there are weird rows in SOTU with majortopic=0 and subtopic=-555)
