### ISSUE TITLE
Missing observations with filters

### ISSUE THREAD

**Issue by reissler** [comparative/cap#160]
In the attached graph, there are no observations, but sometimes there is a dot at 0 and other times it seems as if there is missing data. This only occurs when there is a filter invoked. Also, the 0 line is at the middle of the graph, which seems odd. 
[uFxYpLb4.pdf](https://github.com/comparative/cap/files/131044/uFxYpLb4.pdf)

**Comment by comparative** [comment]
Fixed the 0 line.  The missing points are when there are no results for any topic -- with the filter applied.

i.e. my rule is don't put a point on the graph if the total observation count for that year = 0, and I apply filters to total observation counts... 

changing this behavior would require significant work.
