### ISSUE TITLE
Can't Add MIP Data to Scatterplots

### ISSUE THREAD

**Issue by ejfagan** [comparative/cap#162]
Scatterplots work fine for most datasets. However, I can't add add a scatter plot using the MIP series. To replicate:

Go to trends tool
Add any one series (Say, US hearings on macroeconomics) plus any MIP (Say, US MIP on macroeconomics).
Try to switch to a scatter plot. Nothing happens.

UK MIP has the same problem.

**Comment by comparative** [comment]
Scatter plots only work for the "count" measure.  MIP are datasets where Aggregation Level is set to "percent"... they have no counts and are not eligible for scatter plotting.

App is now protecting itself against this edge case!
