### ISSUE TITLE
New Research Entries Missing Format and Links--Bug

### ISSUE THREAD

**Issue by reissler** [comparative/cap#190]
Hi Geoff,

Hope you had a nice holiday season and start to the new year. Today I was entering a new research entry to the US country page (titled: The Importance of Attention Diversity and How to Measure It). When I hit save and go to look at the front end, the formatting and the links that I created in the WYSIWYG (and are visible from the back end) have disappeared. Could you please take a look at what is going on?

Thanks so much,
Rebecca

**Comment by comparative** [comment]
Fixed!!
